# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d2a32cda8bd10c5b352739cc9c7c9ee62f85536f451ffc4363985d56390e9f163feb8c6fee58fc9470aede365a8e123f1f2e8e485c3b6fc84d62a1accc40368

test:
  secret_key_base: 7395ac60283217529e49df26210ad7efbf613db1064dee1d133aa5d288ade1a3c745168ad2399e94bfb4332b8e1011297c96070140b82afd38d611a3f7c92423

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
